version: "3"

services:
  wordpress_website:
    image: wordpress:latest
    ports:
      - "8090:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "password"
      WORDPRESS_DB_NAME: wordpress
    networks:
      mynetwork:
        

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      mynetwork:
        
volumes:
  mysql:
networks:
  mynetwork:
    ipam:
      driver: default
