# -*- coding: utf-8 -*-
"""SQL

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SgX18rWh1J9FiZZ7n2heTkQBk5AdW08t
"""

#Create a Table
create table students(
student_id int not null,
student_name varchar(50),
age int,
gender varchar(1),
location varchar(100))

#Insert Data in to Table
INSERT into students values(1, 'yaswanth', 25, 'M', 'India')
INSERT into students values(2, 'kishore', 26, 'M', 'USA')

#Quering in to created table
select * from students;

#PRIMARY KEY and FORIEGN KEY
create table dep (
depid int not null,
depname varchar(100),
depaddress varchar(255),
PRIMARY KEY(depid))

create table emp(
empid int,
empname varchar,
empadd varchar,
depid int,
PRIMARY KEY(empid),
FOREIGN KEY(depid) REFERENCES dep(depid))

"""#DATA DEFINITION LANGUAGE
 1.CREATE TABLE

 2.ALTER TABLE
 
 3.DROP TABLE
"""

#CREATE TABLE
create table employees_2022(
emp_name varchar(50),
emp_id int not null,
manager_name varchar(50),
department_id int not null,
PRIMARY KEY(emp_id)
)

#ALTER TABLE - Adding a column
ALTER table
employees_2022
ADD gend varchar(1)

#ALTER TABLE - Rename a column
ALTER table 
employees_2022
RENAME COLUMN gend to gender

#ALTER TABLE - Deleting a column
ALTER TABLE
empoyees_2022
DROP COLUMN gender

#ALTER TABLE - Deleting a table
DROP table <table name>

#ALTER TABLE - Deleting a DB
DROP database <database name>

"""#DATA QUERY LANGUAGE

"""

#INSERT DATA

#Create Table
create table emp_info (first_name varchar(30), last_name varchar(30), id_no int not null, age int not null, city varchar(20), state varchar(20)) 

#Insert Data
INSERT into emp_info values( 'Mary', 'Jones', 99982, 25, 'Payson', 'Arizona' );
INSERT into emp_info values( 'Eric', 'Edwards', 88232, 32, 'San Diego', 'California');
INSERT into emp_info values('Hary Ann', 'Eéwards', 88233, 32, 'Phoenix', 'Arizona');
INSERT into emp_info values( 'Ginger', 'Howell', 980025, 42, 'Cottonwood', 'Arizona');
INSERT into emp_info values('Sebastian', 'Snith', 92001, 23, 'Gila Bend', 'Arizona');
INSERT into emp_info values('Gus', 'Gray', 22352, 35, 'Bagdad', 'Arizona');
INSERT into emp_info values( 'Mary Ann', 'May', 32326, 52, 'Tucson', 'Arizona');
INSERT into emp_info values('Erica', 'Williaes', 32327, 60, 'Showlow' ,'Arizona');
INSERT into emp_info values('Leroy', 'Brown', 32380, 22, 'Pine Top', 'Arizona');
INSERT into emp_info values('Elroy', 'Cleaver', 32382, 22, 'Globe', 'Arizona');

#Query Data
select * from emp_info

#COUNT FUNCTION - for counting 

#COUNT ALL
select COUNT(*) from emp_info

#COUNT SELECTED
select COUNT(age) from emp_info

#QUERY DATA WITH FILTERS

#Filter age above 30
select * from emp_info where age>30;

#Filter age between 30 and 50
select * from emp_info where age>30 and age<50;

#Filter first_name starts with e
select * from emp_info where first_name like 'e%'

#Filter first_name ends with s
select * from emp_info where first_name like '%s'

#Filter first_name containing letter 's'
select * from emp_info where first_name like '%s%'

#Filter ages with exact match
select * from emp_info where age in (22)

#Filter ages with exact match - multiple ages
select * from emp_info where age in (22, 32, 42, 52)

#Filter multiple columns
select * from emp_info where first_name = 'Elroy' and age = 22

"""#DATA MANIPULATION LANGUAGE
1. UPDATE
2.DELETE
"""

#UPDATE
#UPDATE - Elory state to Virginia (single)
update emp_info set state = 'Virginia' where first_name = 'Elroy'

#UPDATE - Elory state to California and age to 25 (Multi)
update emp_info set state = 'California', age = 25 where first_name = 'Elroy'

#DELETE
#DELETE - Delete a row which containing name of Elroy
delete from emp_info where first_name = 'Elroy'